companieshouse/penalty-payment-api

go.mod, go.sum
Update the chs.go dependency to v1.2.4
Resolves: [BI-7501](https://companieshouse.atlassian.net/browse/BI-7501)
=> Update the chs.go dependency to v1.2.4

Dockerfile, README.md, Tiltfile.dev
[SAN-50](https://companieshouse.atlassian.net/browse/SAN-50) Add builder for `$ chs-dev development enable pps-pay-api`
* Baseline image 169942020521.dkr.ecr.eu-west-2.amazonaws.com/local/lfp-pay-api:latest
[SAN-50]: https://companieshouse.atlassian.net/browse/SAN-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-50 Add builder for `$ chs-dev development enable pps-pay-api`

README.md, Tiltfile.dev
[SAN-60](https://companieshouse.atlassian.net/browse/SAN-60) Trigger new release version for pipeline job following rename to `penalty-payment-api`
[SAN-60]: https://companieshouse.atlassian.net/browse/SAN-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-60 Trigger new release version for pipeline job following rename to penalty-payment-api

Makefile, start.sh
- Changes related to chi-config repo changes
=> SAN-115: Refactor penalty-payment-api with repo and pipeline renaming

README.md
Update README to include missing environment variables needed for the dependency, integration https://github.com/companieshouse/go-sdk-manager/tree/master?tab=readme-ov-file#environment-variables
=> SAN-228 Update README

handlers/register.go
=> SAN-231: Revert routing path

.dockerignore, issuer_gateway/api/account_penalties.go, issuer_gateway/private/generate_transaction_list_from_e5_response.go, issuer_gateway/types/transaction_type.go
* Created empty directories for Issuer Gateway
* Created placeholder Go files for the new directories
* Updated Docker ignore file to whitelist 'issuer_gateway' directories
=> SAN-218 Create folder structure for Issuer Gateway

handlers/create_payable_resource.go, issuer_gateway/api/payable_penalty.go, issuer_gateway/api/payable_penalty_test.go, issuer_gateway/private/match_penalty.go, issuer_gateway/private/match_penalty_test.go
* Created PayablePenalty Issuer Gateway API
* Created MatchPenalty Issuer Gateway private function
* Copied and refactored TransactionsArePayable into PayablePenalty and MatchPenalty
* Updated CreatePayableResourceHandler to call the new Issuer Gateway's PayablePenalty
* Refactored existing unit tests and created new tests for acceptable coverage
=> SAN-221 IG Payable Penalty API - Initial Implementation

handlers/payment_details.go, service/payment_details.go, service/payment_details_test.go, transformers/payable_resource.go, transformers/payable_resource_test.go
Refactor penaltyDetailsMap parameter
=> SAN-301: Refactor penaltyDetailsMap parameter

issuer_gateway/private/generate_transaction_list_from_e5_response.go, issuer_gateway/private/generate_transaction_list_from_e5_response_test.go
[SAN-309](https://companieshouse.atlassian.net/browse/SAN-309) Update getPayableStatus to revert isSanctionsPayableStatus / isLFPPayableStatus
* https://github.com/companieshouse/penalty-payment-api/pull/59#discussion_r1981088437
* Also add a few more tests: closed payable status for late filing penalty
[SAN-309]: https://companieshouse.atlassian.net/browse/SAN-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-309 Update getPayableStatus to revert isSanctionsPayableStatus / isLFPPayableStatus

assets/penalty_details.yml, service/payment_details_test.go, transformers/payable_resource_test.go
See bug: https://companieshouse.atlassian.net/browse/SAN-338
See update: https://companieshouse.atlassian.net/browse/SAN-303?focusedCommentId=282107
=> SAN-338 - Revert class of payment to unblock CS journey

assets/penalty_details.yml, service/payment_details_test.go, transformers/payable_resource_test.go
This reverts commit c8858729dda7759baf6dcc716a4c9d62085439bf.
=> Revert SAN-338 - Revert class of payment to unblock CS journey

transformers/payable_resource.go, transformers/payable_resource_test.go
Update resume path to match updated web uri
=> SAN-65: Update resume path to match updated web uri

common/dao/service.go, common/dao/service_test.go, handlers/payment_details_test.go, handlers/penalties_test.go, issuer_gateway/api/account_update_test.go, penalty_payments/interceptors/payable_resource_authentication_test.go, penalty_payments/service/email_service_test.go
=> SAN-481: Increase unit test coverage

assets/penalty_details.yml
Linked PRs:
https://github.com/companieshouse/chs-notification-api/pull/549
=> SAN-22 Add configuration for ROE email confirmation template

issuer_gateway/private/generate_transaction_list.go, issuer_gateway/private/generate_transaction_list_test.go
SAN-468 ROE - Payable scenarios
https://companieshouse.atlassian.net/browse/SAN-468
=> SAN-468 ROE - Payable scenarios

common/utils/reference.go
SAN-501 Replace deprecated libraries in the penalty-payment-api
https://companieshouse.atlassian.net/browse/SAN-501
=> SAN-501 Replace deprecated libraries in the penalty-payment-api

handlers/finance_payment.go
[SAN-428](https://companieshouse.atlassian.net/browse/SAN-428) Fix logging for "Financial penalty payment processing"
[SAN-428]: https://companieshouse.atlassian.net/browse/SAN-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-428 Fix logging for "Financial penalty payment processing"

penalty_payments/consumer/consumer_integration_test.go, testutils/containers.go, testutils/kafka_broker.go
[SAN-589](https://companieshouse.atlassian.net/browse/SAN-589) Update TestIntegrationConsume to use testutils similar to filing-processed-tx-updater
* Image: "bitnami/kafka:3"
[SAN-589]: https://companieshouse.atlassian.net/browse/SAN-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-589 Update TestIntegrationConsume to use testutils similar to filing-processed-tx-updater

penalty_payments/consumer/consumer.go, penalty_payments/consumer/consumer_integration_test.go
[SAN-589](https://companieshouse.atlassian.net/browse/SAN-589) Update TestIntegrationConsume to fix pipeline job (build-test-integration)
[SAN-589]: https://companieshouse.atlassian.net/browse/SAN-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAN-589 Update TestIntegrationConsume to fix pipeline job (build-test-integration)

handlers/create_payable_resource.go
API Anti-Patterns - Refactor CreatePayableResourceHandler
Linked to:
https://companieshouse.atlassian.net/browse/SAN-577
=> SAN-577 API Anti-Patterns - Refactor CreatePayableResourceHandler
